version: '3'

services:
   app:
     build: ./Devops/php
     container_name: app
     volumes:
       - ./src:/var/www/html
     networks:
       - app-network

   app-mysql:
     image: mysql:5.7.22
     container_name: app-mysql
     restart: unless-stopped
     tty: true
     ports:
       - "3306:3306"
     volumes:
       - ./Devops/mysql/dbdata:/var/lib/mysql
       - ./Devops/mysql/my.cnf:/etc/mysql/my.cnf
     environment:
       MYSQL_DATABASE: webtrack
       MYSQL_ROOT_PASSWORD: webtrack
       MYSQL_USER: webtrack
       MYSQL_PASSWORD: webtrack
       SERVICE_TAGS: dev
       SERVICE_NAME: mysql
     networks:
       - app-network

   app-redis:
     image: redis:alpine
     expose:
       - 6379
     networks:
      - app-network

   app-nginx:
     build: ./Devops/nginx
     restart: always
     ports:
       - "80:80"
     volumes:
       - "./src:/var/www/html"
     networks:
       - app-network
     environment:
       VIRTUAL_HOST: webtrack.local,botwebtrack.local

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     ports:
       - 8181:80
     environment:
       - PMA_ARBITRARY=1
     networks:
       - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local